# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  pod 'ZendeskAnswerBotSDK' # AnswerBot-only on the Unified SDK
  pod 'ZendeskChatSDK'      # Chat-only on the Unified SDK
  pod 'ZendeskSupportSDK'   # Support-only on the Unified SDK
  pod 'ZendeskChatProvidersSDK' # for custom UI support


end
